# Generated by Django 3.2.12 on 2022-02-19 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 14, 15, 0, 225940), verbose_name='date published'),
        ),
    ]
